flags:
  generic-deriving:
    base-4-9: false
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.1.0.0
- aeson-pretty-0.8.2
- ansi-terminal-0.6.2.3
- appar-0.1.4
- async-2.1.1
- attoparsec-0.13.1.0
- auto-update-0.1.4
- base-compat-0.9.1
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- case-insensitive-1.2.0.7
- cmdargs-0.10.14
- comonad-5
- contravariant-1.4
- cookie-0.4.2.1
- data-default-class-0.1.2.0
- digest-0.0.1.2
- directory-tree-0.12.1
- distributive-0.5.1
- dlist-0.8.0.2
- easy-file-0.2.1
- exceptions-0.8.3
- fail-4.9.0.0
- fast-logger-2.4.9
- free-4.12.4
- generic-deriving-1.11.1
- hashable-1.2.5.0
- hex-0.1.2
- http-client-0.5.5
- http-date-0.0.6.1
- http-types-0.9.1
- http2-1.6.2
- integer-logarithms-1.0.1
- iproute-1.7.1
- kan-extensions-5.0.1
- lens-4.15.1
- lifted-base-0.2.3.8
- mime-types-0.1.0.7
- mmorph-1.0.9
- monad-control-1.0.1.0
- mtl-2.2.1
- nats-1.1.1
- network-2.6.3.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.0
- parsec-3.1.11
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2
- psqueues-0.2.2.3
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resourcet-1.1.9
- safe-0.3.11
- scientific-0.3.4.10
- scotty-0.11.0
- semigroupoids-5.1
- semigroups-0.18.2
- simple-sendfile-0.2.25
- stm-2.4.4.1
- streaming-commons-0.1.17
- stringsearch-0.3.6.6
- tagged-0.8.5
- temporary-1.2.0.4
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- transformers-0.5.2.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unix-time-0.3.7
- unordered-containers-0.2.7.2
- uuid-types-1.0.3
- vault-0.3.0.6
- vector-0.12.0.0
- void-0.7.1
- wai-3.2.1.1
- wai-extra-3.0.19.1
- wai-logger-2.3.0
- warp-3.2.10
- webdriver-0.8.4
- word8-0.1.2
- zip-archive-0.3.0.5
- zlib-0.6.1.2
resolver: ghc-7.10.3
